#!/bin/sh

set -e
[ -n "$DEBUG" ] && set -x

CONFIG_FILE="$1"
# Config is 1Mb
CONFIG_SIZE_KB=1024

# Slurp the input in a form of a tarball
(cd /conf; tar xf -)

DTS=/conf/eve.dts
if [ -f "$DTS" ]; then
   [ "$(uname -m)" = aarch64 ] && dtc -O dtb -o /conf/eve.dtb -I dts "$DTS"
   rm "$DTS"
fi

#
# Create Config image
#

echo "mtools_skip_check=1" >> /etc/mtools.conf

dd if=/dev/zero of="$CONFIG_FILE" bs=1024 count="$CONFIG_SIZE_KB"
mkfs.vfat -n EVE -v "$CONFIG_FILE" "$CONFIG_SIZE_KB"
mcopy -i "$CONFIG_FILE" -s /conf/* ::/
