#!/bin/sh

set -e
[ -n "$DEBUG" ] && set -x

CONFIG_FILE="$1"
# Config is 1Mb
CONFIG_SIZE_KB=1024

# Slurp the input in a form of a tarball
(cd /conf/raw; tar xf -)

# Traverse /conf to a point where we either see multiple files or no subdirectories
(cd /conf; while cd "$(echo *)" >/dev/null 2>&1 ; do true ; done ; cp -r * /conf ; rm -rf /conf/raw)

DTS=/conf/eve.dts
if [ -f "$DTS" ]; then
   [ "$ZARCH" = arm64 ] && dtc -O dtb -o /conf/eve.dtb -I dts "$DTS"
   rm "$DTS"
fi

#
# Create Config image
#

echo "mtools_skip_check=1" >> /etc/mtools.conf

dd if=/dev/zero of="$CONFIG_FILE" bs=1024 count="$CONFIG_SIZE_KB"
mkfs.vfat -n EVE -v "$CONFIG_FILE" "$CONFIG_SIZE_KB"
mcopy -i "$CONFIG_FILE" -s /conf/* ::/
