FROM lfedge/eve-alpine:12.1.0 AS tools

ENV PKGS="qemu-img tar"
RUN eve-alpine-deploy.sh

FROM lfedge/eve-alpine:12.1.0

COPY --from=tools /out/ /
COPY entrypoint.sh /

ARG TARGETARCH
COPY sdn-${TARGETARCH}-bios.img /bits/sdn-bios.img

ARG SDN_VERSION
RUN echo "$SDN_VERSION" > /bits/sdn-version

WORKDIR /bits
ENTRYPOINT ["/entrypoint.sh"]