#!/bin/sh
# Copyright (c) 2024-2025 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0

mkdir -p "/run/udev/rules.d"

# Start daemon
udevd --daemon
udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices    --action=add
udevadm settle -t 30 || true
