# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/common.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n&com.zededa.cloud.uservice.proto.commonB\006CommonP\001Z$github.com/lf-edge/eve/api/go/common'),
  serialized_pb=_b('\n\x13\x63ommon/common.proto\x12\x06\x63ommon*q\n\rHashAlgorithm\x12\x1a\n\x16HASH_ALGORITHM_INVALID\x10\x00\x12!\n\x1dHASH_ALGORITHM_SHA256_16BYTES\x10\x01\x12!\n\x1dHASH_ALGORITHM_SHA256_32BYTES\x10\x02\x42X\n&com.zededa.cloud.uservice.proto.commonB\x06\x43ommonP\x01Z$github.com/lf-edge/eve/api/go/commonb\x06proto3')
)

_HASHALGORITHM = _descriptor.EnumDescriptor(
  name='HashAlgorithm',
  full_name='common.HashAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HASH_ALGORITHM_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_ALGORITHM_SHA256_16BYTES', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_ALGORITHM_SHA256_32BYTES', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=31,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_HASHALGORITHM)

HashAlgorithm = enum_type_wrapper.EnumTypeWrapper(_HASHALGORITHM)
HASH_ALGORITHM_INVALID = 0
HASH_ALGORITHM_SHA256_16BYTES = 1
HASH_ALGORITHM_SHA256_32BYTES = 2


DESCRIPTOR.enum_types_by_name['HashAlgorithm'] = _HASHALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
