#!/bin/sh

case "$*" in
  *enter*) ctr --namespace services.linuxkit tasks exec -t --exec-id zen zededa-tools bash
           ;;
        *) echo "Welcome to Zenix!"
           echo "  commands: enter"
           ;;
esac 
