#!/bin/sh

CTR_CMD="ctr --namespace services.linuxkit"

help() {
  cat <<__EOT__
Welcome to Zenix!
  commands: enter [qube (assumed zededa-tools)] [command (assumed sh)]
            exec qube command
            list
            status
            start <qube> (requires a qube to be in a destroyed state) 
            pause <qube>
            resume <qube>
            destroy <qube>
__EOT__
  exit 1
}

case "$1" in
    exec) [ -z "$2" -o -z "$3" ] && help
          CONT="$2"
          shift 2
          ${CTR_CMD} t exec --exec-id $(basename $(mktemp)) "$CONT" "$@"
          ;;
   enter) ${CTR_CMD} t exec -t --exec-id $(basename $(mktemp))  ${2:-zededa-tools} ${3:-sh}
          ;;
    list) ${CTR_CMD} c ls
          ;;
  status) ${CTR_CMD} t ls
          ;;
   start) [ -z "$2" ] && help
          ${CTR_CMD} c ls -q | grep -q $2 && echo "ERROR: make sure to run: $0 destroy $2" && help
          /usr/bin/service -v start $2 
          ;;
 destroy) [ -z "$2" ] && help 
          ${CTR_CMD} t kill -a -s SIGKILL $2
          ${CTR_CMD} t delete $2 
          ${CTR_CMD} c rm $2
          ;;
   pause) [ -z "$2" ] && help
          ${CTR_CMD} t pause $2
          ;;
  resume) [ -z "$2" ] && help
          ${CTR_CMD} t resume $2
          ;;
       *) help 
          ;;
esac 
