#!/bin/sh
#
# log-packets [force]
#
# Just a wrapper to call python source or binary.
#
if ls ./lisp-log-packets.pyo >& /dev/null ; then
    python -O ./lisp-log-packets.pyo $1
else
    python ./lisp-log-packets.py $1
fi
