image: eve-edgeview
org: lfedge
config:
  binds:
    - /:/hostfs:ro
    - /dev:/dev:ro
    - /run:/run:ro
    - /run/edgeview:/run/edgeview
    - /persist:/persist:ro
    - /persist/tmp:/persist/tmp
    - /config:/config:ro
    - /etc/resolv.conf:/etc/resolv.conf:ro
    - /proc:/host/proc:ro
  capabilities:
    - all
  net: host
  pid: host
  devices:
    - path: all
      type: a
