// @generated by pkg/pillar/types/monitorapi/internal/gen — DO NOT EDIT.

package monitorapi

import (
	"encoding/json"
	"fmt"
	"net/netip"
)

// marshalTagged emits an internally-tagged object: {"<key>":"<tag>", ...fields}.
func marshalTagged(key, tag string, v any) ([]byte, error) {
	inner, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	prefix := fmt.Sprintf("{%q:%q", key, tag)
	if string(inner) == "{}" {
		return []byte(prefix + "}"), nil
	}
	return append([]byte(prefix+","), inner[1:]...), nil
}

func (v MediaCellular) MarshalJSON() ([]byte, error) {
	type alias MediaCellular
	return marshalTagged("kind", "cellular", alias(v))
}

func (v MediaEthernet) MarshalJSON() ([]byte, error) {
	type alias MediaEthernet
	return marshalTagged("kind", "ethernet", alias(v))
}

func (v MediaWifi) MarshalJSON() ([]byte, error) {
	type alias MediaWifi
	return marshalTagged("kind", "wifi", alias(v))
}

// UnmarshalNetworkMedia decodes an internally-tagged NetworkMedia.
func UnmarshalNetworkMedia(b []byte) (NetworkMedia, error) {
	var disc struct {
		Tag string `json:"kind"`
	}
	if err := json.Unmarshal(b, &disc); err != nil {
		return nil, err
	}
	switch disc.Tag {
	case "cellular":
		var v MediaCellular
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "ethernet":
		var v MediaEthernet
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "wifi":
		var v MediaWifi
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown NetworkMedia kind %q", disc.Tag)
	}
}

func (v ProxyManual) MarshalJSON() ([]byte, error) {
	type alias ProxyManual
	return marshalTagged("mode", "manual", alias(v))
}

func (v ProxyNone) MarshalJSON() ([]byte, error) {
	type alias ProxyNone
	return marshalTagged("mode", "none", alias(v))
}

func (v ProxyPac) MarshalJSON() ([]byte, error) {
	type alias ProxyPac
	return marshalTagged("mode", "pac", alias(v))
}

func (v ProxyWpad) MarshalJSON() ([]byte, error) {
	type alias ProxyWpad
	return marshalTagged("mode", "wpad", alias(v))
}

// UnmarshalProxySettings decodes an internally-tagged ProxySettings.
func UnmarshalProxySettings(b []byte) (ProxySettings, error) {
	var disc struct {
		Tag string `json:"mode"`
	}
	if err := json.Unmarshal(b, &disc); err != nil {
		return nil, err
	}
	switch disc.Tag {
	case "manual":
		var v ProxyManual
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "none":
		var v ProxyNone
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "pac":
		var v ProxyPac
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "wpad":
		var v ProxyWpad
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown ProxySettings mode %q", disc.Tag)
	}
}

func (v VaultDisabled) MarshalJSON() ([]byte, error) {
	type alias VaultDisabled
	return marshalTagged("state", "disabled", alias(v))
}

func (v VaultLocked) MarshalJSON() ([]byte, error) {
	type alias VaultLocked
	return marshalTagged("state", "locked", alias(v))
}

func (v VaultUnknown) MarshalJSON() ([]byte, error) {
	type alias VaultUnknown
	return marshalTagged("state", "unknown", alias(v))
}

func (v VaultUnlocked) MarshalJSON() ([]byte, error) {
	type alias VaultUnlocked
	return marshalTagged("state", "unlocked", alias(v))
}

// UnmarshalVaultStatus decodes an internally-tagged VaultStatus.
func UnmarshalVaultStatus(b []byte) (VaultStatus, error) {
	var disc struct {
		Tag string `json:"state"`
	}
	if err := json.Unmarshal(b, &disc); err != nil {
		return nil, err
	}
	switch disc.Tag {
	case "disabled":
		var v VaultDisabled
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "locked":
		var v VaultLocked
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "unknown":
		var v VaultUnknown
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "unlocked":
		var v VaultUnlocked
		if err := json.Unmarshal(b, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown VaultStatus state %q", disc.Tag)
	}
}

func (x *NetworkInterface) UnmarshalJSON(b []byte) error {
	var raw struct {
		Name    string          `json:"name"`
		Label   string          `json:"label"`
		MAC     string          `json:"mac"`
		Up      bool            `json:"up"`
		IsMgmt  bool            `json:"isMgmt"`
		Cost    uint8           `json:"cost"`
		Media   json.RawMessage `json:"media"`
		Network PortNetwork     `json:"network"`
		VLANs   []VLAN          `json:"vlans"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	x.Name = raw.Name
	x.Label = raw.Label
	x.MAC = raw.MAC
	x.Up = raw.Up
	x.IsMgmt = raw.IsMgmt
	x.Cost = raw.Cost
	if len(raw.Media) > 0 {
		v, err := UnmarshalNetworkMedia(raw.Media)
		if err != nil {
			return err
		}
		x.Media = v
	}
	x.Network = raw.Network
	x.VLANs = raw.VLANs
	return nil
}

func (x *NetworkProxy) UnmarshalJSON(b []byte) error {
	var raw struct {
		Port  string          `json:"port"`
		Proxy json.RawMessage `json:"proxy"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	x.Port = raw.Port
	if len(raw.Proxy) > 0 {
		v, err := UnmarshalProxySettings(raw.Proxy)
		if err != nil {
			return err
		}
		x.Proxy = v
	}
	return nil
}

func (x *PortNetwork) UnmarshalJSON(b []byte) error {
	var raw struct {
		IsDHCP     bool            `json:"isDhcp"`
		IPv4       []netip.Addr    `json:"ipv4"`
		IPv6       []netip.Addr    `json:"ipv6"`
		Subnet     *netip.Prefix   `json:"subnet"`
		Routes     []netip.Addr    `json:"routes"`
		DNSServers []netip.Addr    `json:"dnsServers"`
		NTPServers []string        `json:"ntpServers"`
		Domain     string          `json:"domain"`
		Proxy      json.RawMessage `json:"proxy"`
		Errors     []string        `json:"errors"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	x.IsDHCP = raw.IsDHCP
	x.IPv4 = raw.IPv4
	x.IPv6 = raw.IPv6
	x.Subnet = raw.Subnet
	x.Routes = raw.Routes
	x.DNSServers = raw.DNSServers
	x.NTPServers = raw.NTPServers
	x.Domain = raw.Domain
	if len(raw.Proxy) > 0 {
		v, err := UnmarshalProxySettings(raw.Proxy)
		if err != nil {
			return err
		}
		x.Proxy = v
	}
	x.Errors = raw.Errors
	return nil
}
