FROM alpine:3.12 as tools
RUN mkdir -p /out/etc/apk /out/boot && cp -r /etc/apk/* /out/etc/apk/
RUN apk add --no-cache --initdb -p /out qemu-img=5.0.0-r2 tar=1.32-r1 uboot-tools=2020.04-r0 coreutils=8.32-r0
# hadolint ignore=DL3006
FROM MKISO_TAG as iso
# hadolint ignore=DL3006
FROM IPXE_TAG as ipxe
# hadolint ignore=DL3006
FROM MKRAW_TAG as raw
# we need to get rid of embedded initrd since we will get it from outside
RUN rm /initrd.img
# hadolint ignore=DL3006
FROM MKCONF_TAG as conf

COPY --from=iso / /
COPY --from=raw / /
COPY --from=ipxe / /
COPY --from=tools /out/ /
COPY installer /bits
COPY runme.sh /
RUN mkdir /in /out


# These labels indicate where each component type is.
# These must be updated if we change filenames or locations.
# The annotations to be used are available at https://github.com/lf-edge/edge-containers/blob/master/docs/annotations.md
LABEL org.lfedge.eci.artifact.root="/bits/rootfs.img"
LABEL org.lfedge.eci.artifact.initrd="/bits/initrd.img"

WORKDIR /bits
ENTRYPOINT ["/runme.sh"]
