# linuxkit build template 
#
# Copyright (c) 2018 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
org: lfedge
image: eve-storage-init
config:
  binds:
    - /:/hostfs
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /var:/var
    - /persist:/persist:rshared,rbind
    - /config:/config:rshared,rbind
    - /containers:/containers:rshared,rbind
  rootfsPropagation: shared
  capabilities:
    - all
  devices:
    - path: all
      type: a
