FROM PILLAR_TAG as pillar
FROM alpine:3.10.3
WORKDIR /
# hadolint ignore=DL3018
RUN apk add --no-cache bash glib squashfs-tools util-linux e2fsprogs \
        e2fsprogs-extra keyutils dosfstools coreutils libpcap-dev
COPY storage-init.sh /storage-init.sh
COPY --from=pillar /opt/zededa/bin/fscrypt /usr/bin/fscrypt
COPY --from=pillar /opt/zededa/bin/vaultmgr /usr/bin/vaultmgr

ENTRYPOINT []
CMD ["/storage-init.sh"]
