---
run:
  deadline: 30m

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax  # allow unless explicitly denied
        files:
          - $all
        allow:
          - $gostd
          - $ven

linters:
  enable-all: true
  disable:
    - gochecknoglobals  # unreliable
    - lll               # line length check
    - mnd               # troublesome with little value
    - stylecheck        # covered by revive
    - typecheck         # See golangci/golangci-lint#419
    - varnamelen        # Too opinionated about var length
    - funlen            # function length checks
    - godot             # Don't mandate periods at end of comments
    - nlreturn          # Too opioniated about whitespace
    - wsl               # Way to opinionated
    - whitespace        # Too opinionated about whitespace
    - wrapcheck         # XXX should we switch to wrapped errors etc?
    - err113            # Too opinioned about error handling (also yetus probably doesn't run it correctly)
    - gofumpt           # Too opinionated about whitespace
    - gocognit          # Too opinionated on existing code
    - gocyclo           # Too opinionated on existing code
    - nestif            # Too opinionated on existing code
    - exhaustruct       # Too opinionated on existing code
    - nonamedreturns    # Named return is not a bad practice
    - cyclop            # Raises warnings even for relatively simple functions
    - ireturn           # Returning interfaces is a common practise for constructors in defensive programming
    - exhaustive        # Complains even if struct has default branch
    - musttag           # pillar uses implicit tags for all structs
    - maintidx          # Disable maintainability index
    - tenv              # Deprecated
    - dupl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# yetus expects stable output from linter
# that is we should return all errors
# not only the first hit
output:
  issues.uniq-by-line: false
