# linuxkit build template 
#
# Copyright (c) 2018 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
org: lfedge
image: eve-pillar
network: yes
config:
  binds:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /var/config:/config
    - /var/log:/var/log/dom0
    - /:/hostfs
    - /etc/eve-release:/etc/eve-release
  net: host
  capabilities:
    - all
  pid: host
