---
name: 'Run EVE make comand'
description: 'Fetch tags, login to dockerhub, build and push artifacts produced by make command'

inputs:
  command:
    required: true
    type: string
  dockerhub-token:
    required: true
    type: string
  dockerhub-account:
    required: true
    type: string
  clean:
    required: false
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
    - name: Force fetch annotated tags (workaround)
      # Workaround for https://github.com/actions/checkout/issues/290
      run: |
        git fetch --force --tags
      shell: bash
    - name: Login to Docker Hub
      if: ${{ github.event.repository.full_name }}== 'lf-edge/eve'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-account }}
        password: ${{ inputs.dockerhub-token }}
    - name: Running `make -e ${{ inputs.command }}`
      run: |
        make -e ${{ inputs.command }}
      shell: bash
    - name: Post `make -e ${{ inputs.command }}` report
      run: |
        echo Disk usage
        df -h
        echo Memory
        free -m
        docker system df
        docker system df -v
      shell: bash
    - name: Pre clean report
      if: ${{ inputs.clean == 'true' }}
      run: |
        echo Disk usage
        df -h
        echo Memory
        free -m
        docker system df
        docker system df -v
      shell: bash
    - name: Clean
      if: ${{ inputs.clean == 'true' }}
      run: |
        make clean
        docker system prune -f -a
        rm -rf ~/.linuxkit
      shell: bash
