name: 'Run EVE make comand'
description: 'Fetch tags, login to dockerhub, build and push artifacts produced by make command'

inputs:
  command:
    required: true
    type: string
  dockerhub-token:
    required: true
    type: string
  dockerhub-account:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Force fetch annotated tags (workaround)
      # Workaround for https://github.com/actions/checkout/issues/290
      run: |
        git fetch --force --tags
    - name: Login to DockerHUB
      run: |
        echo "${{ inputs.dockerhub-token }}" |\
           docker login -u "${{ inputs.dockerhub-account }}" --password-stdin
    - name: Build and push `make -e ${{ inputs.command }}`
      run: |
        make -e ${{ inputs.command }}
    - name: Post `make -e ${{ inputs.command }}` report
      run: |
        echo Disk usage
        df -h
        echo Memory
        free -m
        docker system df
        docker system df -v
    - name: Pre clean report
      run: |
        echo Disk usage
        df -h
        echo Memory
        free -m
        docker system df
        docker system df -v
    - name: Clean
      run: |
        make clean
        docker system prune -f -a
        rm -rf ~/.linuxkit
