# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eveuuid/eveuuid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eveuuid/eveuuid.proto',
  package='org.lfedge.eve.eveuuid',
  syntax='proto3',
  serialized_options=b'\n\032com.org.lfedge.eve.eveuuidB\007EveUuidP\001Z\007eveuuid',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x65veuuid/eveuuid.proto\x12\x16org.lfedge.eve.eveuuid\"\r\n\x0bUuidRequest\"H\n\x0cUuidResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x14\n\x0cproduct_name\x18\x03 \x01(\tB0\n\x1a\x63om.org.lfedge.eve.eveuuidB\x07\x45veUuidP\x01Z\x07\x65veuuidb\x06proto3'
)




_UUIDREQUEST = _descriptor.Descriptor(
  name='UuidRequest',
  full_name='org.lfedge.eve.eveuuid.UuidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=62,
)


_UUIDRESPONSE = _descriptor.Descriptor(
  name='UuidResponse',
  full_name='org.lfedge.eve.eveuuid.UuidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.lfedge.eve.eveuuid.UuidResponse.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='org.lfedge.eve.eveuuid.UuidResponse.manufacturer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_name', full_name='org.lfedge.eve.eveuuid.UuidResponse.product_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['UuidRequest'] = _UUIDREQUEST
DESCRIPTOR.message_types_by_name['UuidResponse'] = _UUIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UuidRequest = _reflection.GeneratedProtocolMessageType('UuidRequest', (_message.Message,), {
  'DESCRIPTOR' : _UUIDREQUEST,
  '__module__' : 'eveuuid.eveuuid_pb2'
  # @@protoc_insertion_point(class_scope:org.lfedge.eve.eveuuid.UuidRequest)
  })
_sym_db.RegisterMessage(UuidRequest)

UuidResponse = _reflection.GeneratedProtocolMessageType('UuidResponse', (_message.Message,), {
  'DESCRIPTOR' : _UUIDRESPONSE,
  '__module__' : 'eveuuid.eveuuid_pb2'
  # @@protoc_insertion_point(class_scope:org.lfedge.eve.eveuuid.UuidResponse)
  })
_sym_db.RegisterMessage(UuidResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
