#!/bin/sh

if test -f /proc/vmcore; then
    # NOOP if dump-capture kernel
    exit 0;
fi

# Create 'memory' controller for the 'memlogd' making it part
# of the eve/services
mkdir -p /sys/fs/cgroup/memory/eve/services/memlogd

# Add 'memlogd' to the 'memory' controller. Further 'memlogd'
# cgroup changes happen in the 010-eve-cgroup, see all the
# details there.
echo $$ > /sys/fs/cgroup/memory/eve/services/memlogd/tasks

/usr/bin/memlogd -daemonize -max-line-len 8192
