#!/bin/sh
#
# assume that if we can't tell what partition we're
# running from it means we're running from memory
ID=$(zboot curpart 2>/dev/null)
echo "${ID:-RAM}" > /run/eve.id
cp -p /etc/eve-release /run/eve-release
cp -p /etc/eve-hv-type /run/eve-hv-type
