#!/bin/sh

default_cgroup_memory_limit=1000000000 #1GB
default_cgroup_cpus_limit='0-1'

dom0_cgroup_memory_soft_limit=$(cat /proc/cmdline | grep -o '\bdom0_mem=[^, ]*' | cut -d = -f 2)
dom0_cgroup_memory_limit=$(cat /proc/cmdline | grep -o "\bdom0_mem=[^,]*,max:[^ ]*" | cut -d : -f 2)
dom0_cgroup_cpus_limit="0-$(cat /proc/cmdline | grep -o '\bdom0_max_vcpus=[^ ]*' | cut -d = -f 2)"

eve_cgroup_memory_soft_limit=$(cat /proc/cmdline | grep -o '\beve_mem=[^, ]*' | cut -d = -f 2)
eve_cgroup_memory_limit=$(cat /proc/cmdline | grep -o "\beve_mem=[^,]*,max:[^ ]*" | cut -d : -f 2)
eve_cgroup_cpus_limit="0-$(cat /proc/cmdline | grep -o '\beve_max_vcpus=[^ ]*' | cut -d = -f 2)"

ctrd_cgroup_memory_soft_limit=$(cat /proc/cmdline | grep -o '\bctrd_mem=[^, ]*' | cut -d = -f 2)
ctrd_cgroup_memory_limit=$(cat /proc/cmdline | grep -o "\bctrd_mem=[^,]*,max:[^ ]*" | cut -d : -f 2)
ctrd_cgroup_cpus_limit="0-$(cat /proc/cmdline | grep -o '\bctrd_max_vcpus=[^ ]*' | cut -d = -f 2)"

if [ -z "${dom0_cgroup_memory_soft_limit}" ]; then
    echo "Setting default value of $default_cgroup_memory_limit for dom0_cgroup_memory_soft_limit"
    dom0_cgroup_memory_soft_limit=$default_cgroup_memory_limit
fi

if [ -z "${dom0_cgroup_memory_limit}" ]; then
    echo "Setting value of $dom0_cgroup_memory_soft_limit for dom0_cgroup_memory_limit"
    dom0_cgroup_memory_limit=$dom0_cgroup_memory_soft_limit
fi

if [ "$dom0_cgroup_cpus_limit" == "0-" ]; then
    echo "Setting default value of $default_cgroup_cpus_limit for dom0_cgroup_cpus_limit"
    dom0_cgroup_cpus_limit=$default_cgroup_cpus_limit
fi

if [ -z "${eve_cgroup_memory_soft_limit}" ]; then
    echo "Setting default value of $default_cgroup_memory_limit for eve_cgroup_memory_soft_limit"
    eve_cgroup_memory_soft_limit=$default_cgroup_memory_limit
fi

if [ -z "${eve_cgroup_memory_limit}" ]; then
    echo "Setting value of $eve_cgroup_memory_soft_limit for eve_cgroup_memory_limit"
    eve_cgroup_memory_limit=$eve_cgroup_memory_soft_limit
fi

if [ "$eve_cgroup_cpus_limit" == "0-" ]; then
    echo "Setting default value of $default_cgroup_cpus_limit for eve_cgroup_cpus_limit"
    eve_cgroup_cpus_limit=$default_cgroup_cpus_limit
fi

if [ -z "${ctrd_cgroup_memory_soft_limit}" ]; then
    echo "Setting default value of $default_cgroup_memory_limit for ctrd_cgroup_memory_soft_limit"
    ctrd_cgroup_memory_soft_limit=$default_cgroup_memory_limit
fi

if [ -z "${ctrd_cgroup_memory_limit}" ]; then
    echo "Setting value of $ctrd_cgroup_memory_soft_limit for ctrd_cgroup_memory_limit"
    ctrd_cgroup_memory_limit=$ctrd_cgroup_memory_soft_limit
fi

if [ "$ctrd_cgroup_cpus_limit" == "0-" ]; then
    echo "Setting default value of $default_cgroup_cpus_limit for ctrd_cgroup_cpus_limit"
    ctrd_cgroup_cpus_limit=$default_cgroup_cpus_limit
fi

CGROUPS="cpuset cpu cpuacct blkio memory devices freezer net_cls perf_event net_prio hugetlb pids systemd "
EVESRVICES="rsyslogd ntpd sshd wwan wlan lisp guacd pillar vtpm watchdog xen-tools "

#Creating eve cgroup which will be parent/dom0 cgroup
for cg in $CGROUPS; do
    mkdir -p /sys/fs/cgroup/"${cg}"/eve
done

#Creating cgroup for individual eve services
for srv in $EVESRVICES; do
    for cg in $CGROUPS; do
        mkdir -p /sys/fs/cgroup/"${cg}"/eve/services/"${srv}"
    done
done

#Creating cgroup for containerd
mkdir -p /sys/fs/cgroup/memory/eve/containerd

#Creating cgroup for memlogd
for cg in $CGROUPS; do
    mkdir -p /sys/fs/cgroup/"${cg}"/eve/memlogd
done

/bin/echo $dom0_cgroup_memory_limit > /sys/fs/cgroup/memory/eve/memory.limit_in_bytes
/bin/echo $dom0_cgroup_memory_soft_limit > /sys/fs/cgroup/memory/eve/memory.soft_limit_in_bytes
/bin/echo $dom0_cgroup_cpus_limit > /sys/fs/cgroup/cpuset/eve/cpuset.cpus

/bin/echo $ctrd_cgroup_memory_limit > /sys/fs/cgroup/memory/eve/containerd/memory.limit_in_bytes
/bin/echo $ctrd_cgroup_memory_soft_limit > /sys/fs/cgroup/memory/eve/containerd/memory.soft_limit_in_bytes

/bin/echo $eve_cgroup_memory_limit > /sys/fs/cgroup/memory/eve/services/memory.limit_in_bytes
/bin/echo $eve_cgroup_memory_soft_limit > /sys/fs/cgroup/memory/eve/services/memory.soft_limit_in_bytes
/bin/echo $eve_cgroup_cpus_limit > /sys/fs/cgroup/cpuset/eve/services/cpuset.cpus

for srv in $EVESRVICES; do
    /bin/echo $eve_cgroup_memory_limit > /sys/fs/cgroup/memory/eve/services/"${srv}"/memory.limit_in_bytes
    /bin/echo $eve_cgroup_memory_soft_limit > /sys/fs/cgroup/memory/eve/services/"${srv}"/memory.soft_limit_in_bytes
    /bin/echo $eve_cgroup_cpus_limit > /sys/fs/cgroup/cpuset/eve/services/"${srv}"/cpuset.cpus
done
