// Copyright (c) 2026 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// gen-hash-deps reads .gen-deps/.bootstrap/*.hash YAML files and emits a
// hash-deps.mk file containing two sections:
//   1. Hash file dependency rules — .gen-deps/X.hash depends on .gen-deps/Y.hash
//      for every Y that X depends on.  Because .gen-deps/%.hash is a real file
//      target whose recipe runs linuxkit pkg build, these deps drive both build
//      ordering (Y is built before X) and cache invalidation (X rebuilds when
//      Y's hash file is updated after a Y rebuild).
//   2. Cache-export ordering rules (consumers after deps).
//
// Usage: gen-hash-deps -d <bootstrap-hash-dir> [-b <build-hash-dir>] -o <output.mk>
//
//   -d  directory containing .hash files written by linuxkit pkg update-hashes
//       (used as input for dep graph extraction only)
//   -b  directory prefix used in the generated make rules; defaults to -d
//       Set -b .gen-deps when bootstrap hashes live in .gen-deps/.bootstrap
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// hashManifest mirrors pkglib.HashManifest from linuxkit.
type hashManifest struct {
	Tag      string     `yaml:"tag"`
	BuildYML string     `yaml:"build-yml"`
	Deps     []depEntry `yaml:"deps,omitempty"`
}

type depEntry struct {
	Path string `yaml:"path"`
	Tag  string `yaml:"tag"`
}

func pkgName(pkgPath string) string {
	return filepath.Base(pkgPath)
}

func main() {
	var (
		hashDir  string
		buildDir string
		outFile  string
	)
	flag.StringVar(&hashDir, "d", ".gen-deps", "Directory containing .hash files (input)")
	flag.StringVar(&buildDir, "b", "", "Directory prefix used in generated rules (default: same as -d)")
	flag.StringVar(&outFile, "o", ".gen-deps/hash-deps.mk", "Output make file")
	flag.Parse()

	if buildDir == "" {
		buildDir = hashDir
	}

	// Read all .hash files.
	pattern := filepath.Join(hashDir, "*.hash")
	hashFiles, err := filepath.Glob(pattern)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-hash-deps: globbing %s: %v\n", pattern, err)
		os.Exit(1)
	}

	type pkgDeps struct {
		name    string   // e.g. "dom0-ztools"
		depPkgs []string // dep pkg names, e.g. ["zfs", "alpine"]
	}

	var entries []pkgDeps
	for _, hf := range hashFiles {
		b, err := os.ReadFile(hf)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-hash-deps: reading %s: %v\n", hf, err)
			os.Exit(1)
		}
		var m hashManifest
		if err := yaml.Unmarshal(b, &m); err != nil {
			fmt.Fprintf(os.Stderr, "gen-hash-deps: parsing %s: %v\n", hf, err)
			os.Exit(1)
		}
		if len(m.Deps) == 0 {
			continue
		}
		name := strings.TrimSuffix(filepath.Base(hf), ".hash")
		var depNames []string
		for _, d := range m.Deps {
			depNames = append(depNames, pkgName(d.Path))
		}
		entries = append(entries, pkgDeps{name: name, depPkgs: depNames})
	}

	// Sort for deterministic output.
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	var sb strings.Builder
	sb.WriteString("# .gen-deps/hash-deps.mk — generated by tools/gen-hash-deps. DO NOT EDIT.\n")
	sb.WriteString("# Re-run 'make update-hashes' to regenerate.\n\n")

	// Section 1: hash file dependency rules.
	// These prereq-only rules (no recipe) are merged by make with the
	// .gen-deps/%.hash pattern rule in the Makefile, which provides the recipe.
	// They serve dual purpose: build ordering (dep built before consumer) and
	// cache invalidation (consumer hash file is out-of-date when dep hash file
	// is updated after a dep rebuild, triggering a consumer rebuild).
	sb.WriteString("# Hash file deps (build ordering + cache invalidation):\n")
	for _, e := range entries {
		var depFiles []string
		for _, dep := range e.depPkgs {
			depFiles = append(depFiles, filepath.Join(buildDir, dep+".hash"))
		}
		sort.Strings(depFiles)
		fmt.Fprintf(&sb, "%s: %s\n",
			filepath.Join(buildDir, e.name+".hash"),
			strings.Join(depFiles, " "))
	}

	// Section 2: cache-export ordering (consumers after deps).
	sb.WriteString("\n# Cache-export ordering (Section 2 — consumers after deps):\n")
	for _, e := range entries {
		for _, dep := range e.depPkgs {
			fmt.Fprintf(&sb, "%s-cache-export-docker-load: %s-cache-export-docker-load\n",
				e.name, dep)
		}
	}

	if err := os.WriteFile(outFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-hash-deps: writing %s: %v\n", outFile, err)
		os.Exit(1)
	}
}
