// gen-hash-deps reads .gen-deps/*.hash YAML files and emits a hash-deps.mk file
// containing two sections:
//   1. Hash file dependency rules — make rebuilds .gen-deps/X.hash when a dep's
//      hash file changes (ordering + invalidation for file-target builds).
//   2. Cache-export ordering rules (consumers after deps).
//
// Section 3 (eve-% ordering) is NOT needed: the file-target dep chain in Section 1
// combined with the .gen-deps/%.hash build recipe handles ordering naturally.
//
// Usage: gen-hash-deps -d <hash-dir> -o <output.mk>
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// hashManifest mirrors pkglib.HashManifest from linuxkit.
type hashManifest struct {
	Tag      string     `yaml:"tag"`
	BuildYML string     `yaml:"build-yml"`
	Deps     []depEntry `yaml:"deps,omitempty"`
}

type depEntry struct {
	Path string `yaml:"path"`
	Tag  string `yaml:"tag"`
}

func pkgName(pkgPath string) string {
	return filepath.Base(pkgPath)
}

func main() {
	var (
		hashDir string
		outFile string
	)
	flag.StringVar(&hashDir, "d", ".gen-deps", "Directory containing .hash files")
	flag.StringVar(&outFile, "o", ".gen-deps/hash-deps.mk", "Output make file")
	flag.Parse()

	// Read all .hash files.
	pattern := filepath.Join(hashDir, "*.hash")
	hashFiles, err := filepath.Glob(pattern)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-hash-deps: globbing %s: %v\n", pattern, err)
		os.Exit(1)
	}

	type pkgDeps struct {
		name    string   // e.g. "dom0-ztools"
		depPkgs []string // dep pkg names, e.g. ["zfs", "alpine"]
	}

	var entries []pkgDeps
	for _, hf := range hashFiles {
		b, err := os.ReadFile(hf)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-hash-deps: reading %s: %v\n", hf, err)
			os.Exit(1)
		}
		var m hashManifest
		if err := yaml.Unmarshal(b, &m); err != nil {
			fmt.Fprintf(os.Stderr, "gen-hash-deps: parsing %s: %v\n", hf, err)
			os.Exit(1)
		}
		if len(m.Deps) == 0 {
			continue
		}
		name := strings.TrimSuffix(filepath.Base(hf), ".hash")
		var depNames []string
		for _, d := range m.Deps {
			depNames = append(depNames, pkgName(d.Path))
		}
		entries = append(entries, pkgDeps{name: name, depPkgs: depNames})
	}

	// Sort for deterministic output.
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	var sb strings.Builder
	sb.WriteString("# .gen-deps/hash-deps.mk — generated by tools/gen-hash-deps. DO NOT EDIT.\n")
	sb.WriteString("# Re-run 'make update-hashes' to regenerate.\n\n")

	// Section 1: hash file dependency rules.
	// These prereq-only rules (no recipe) are merged by make with the static
	// .gen-deps/%.hash pattern rule in the Makefile, which provides the recipe.
	sb.WriteString("# Hash file deps (trigger pattern rule rebuild when dep tag changes):\n")
	for _, e := range entries {
		var depFiles []string
		for _, dep := range e.depPkgs {
			depFiles = append(depFiles, filepath.Join(hashDir, dep+".hash"))
		}
		sort.Strings(depFiles)
		fmt.Fprintf(&sb, "%s: %s\n",
			filepath.Join(hashDir, e.name+".hash"),
			strings.Join(depFiles, " "))
	}

	// Section 2: cache-export ordering (consumers after deps).
	sb.WriteString("\n# Cache-export ordering (Section 2 — consumers after deps):\n")
	for _, e := range entries {
		for _, dep := range e.depPkgs {
			fmt.Fprintf(&sb, "%s-cache-export-docker-load: %s-cache-export-docker-load\n",
				e.name, dep)
		}
	}

	if err := os.WriteFile(outFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-hash-deps: writing %s: %v\n", outFile, err)
		os.Exit(1)
	}
}
