image: eve-newlog
org: lfedge
config:
  binds:
    - /dev:/dev
    - /run:/run
    - /persist:/persist
    - /config:/config
  capabilities:
    - all
  net: host
  pid: host
  devices:
    - path: all
      type: a
