# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import devcommon_pb2 as devcommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x1a\x0f\x64\x65vcommon.proto\"&\n\x13ServiceOpaqueConfig\x12\x0f\n\x07oconfig\x18\x01 \x01(\t\"\xc3\x01\n\x11ServiceLispConfig\x12 \n\x07LispMSs\x18\x01 \x03(\x0b\x32\x0f.ZcServicePoint\x12\x16\n\x0eLispInstanceId\x18\x02 \x01(\r\x12\x10\n\x08\x61llocate\x18\x03 \x01(\x08\x12\x15\n\rexportprivate\x18\x04 \x01(\x08\x12\x18\n\x10\x61llocationprefix\x18\x05 \x01(\x0c\x12\x1b\n\x13\x61llocationprefixlen\x18\x06 \x01(\r\x12\x14\n\x0c\x45xperimental\x18\x14 \x01(\x08\"\xda\x01\n\x15ServiceInstanceConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64isplayname\x18\x02 \x01(\t\x12\x1a\n\x07srvtype\x18\x03 \x01(\x0e\x32\t.ZSrvType\x12\x10\n\x08\x61\x63tivate\x18\x05 \x01(\x08\x12\x0f\n\x07\x61pplink\x18\n \x01(\t\x12\x19\n\x07\x64\x65vlink\x18\x14 \x01(\x0b\x32\x08.Adapter\x12!\n\x03\x63\x66g\x18\x1e \x01(\x0b\x32\x14.ServiceOpaqueConfig\x12#\n\x07lispCfg\x18\x1f \x01(\x0b\x32\x12.ServiceLispConfig*s\n\x08ZSrvType\x12\r\n\tZsrvFirst\x10\x00\x12\x12\n\x0eZsrvStrongSwan\x10\x01\x12\x0c\n\x08ZsrvLISP\x10\x02\x12\x0e\n\nZsrvBridge\x10\x03\x12\x0b\n\x07ZsrvNAT\x10\x04\x12\n\n\x06ZsrvLB\x10\x05\x12\r\n\x08ZsrvLast\x10\xff\x01\x42G\n\x1f\x63om.zededa.cloud.uservice.protoZ$github.com/zededa/eve/sdk/go/zconfigb\x06proto3')
  ,
  dependencies=[devcommon__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ZSRVTYPE = _descriptor.EnumDescriptor(
  name='ZSrvType',
  full_name='ZSrvType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZsrvFirst', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvStrongSwan', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvLISP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvBridge', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvNAT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvLB', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZsrvLast', index=6, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=493,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_ZSRVTYPE)

ZSrvType = enum_type_wrapper.EnumTypeWrapper(_ZSRVTYPE)
ZsrvFirst = 0
ZsrvStrongSwan = 1
ZsrvLISP = 2
ZsrvBridge = 3
ZsrvNAT = 4
ZsrvLB = 5
ZsrvLast = 255



_SERVICEOPAQUECONFIG = _descriptor.Descriptor(
  name='ServiceOpaqueConfig',
  full_name='ServiceOpaqueConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oconfig', full_name='ServiceOpaqueConfig.oconfig', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=72,
)


_SERVICELISPCONFIG = _descriptor.Descriptor(
  name='ServiceLispConfig',
  full_name='ServiceLispConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LispMSs', full_name='ServiceLispConfig.LispMSs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LispInstanceId', full_name='ServiceLispConfig.LispInstanceId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allocate', full_name='ServiceLispConfig.allocate', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exportprivate', full_name='ServiceLispConfig.exportprivate', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allocationprefix', full_name='ServiceLispConfig.allocationprefix', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allocationprefixlen', full_name='ServiceLispConfig.allocationprefixlen', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Experimental', full_name='ServiceLispConfig.Experimental', index=6,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=270,
)


_SERVICEINSTANCECONFIG = _descriptor.Descriptor(
  name='ServiceInstanceConfig',
  full_name='ServiceInstanceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ServiceInstanceConfig.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayname', full_name='ServiceInstanceConfig.displayname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srvtype', full_name='ServiceInstanceConfig.srvtype', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activate', full_name='ServiceInstanceConfig.activate', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applink', full_name='ServiceInstanceConfig.applink', index=4,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devlink', full_name='ServiceInstanceConfig.devlink', index=5,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg', full_name='ServiceInstanceConfig.cfg', index=6,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lispCfg', full_name='ServiceInstanceConfig.lispCfg', index=7,
      number=31, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=491,
)

_SERVICELISPCONFIG.fields_by_name['LispMSs'].message_type = devcommon__pb2._ZCSERVICEPOINT
_SERVICEINSTANCECONFIG.fields_by_name['srvtype'].enum_type = _ZSRVTYPE
_SERVICEINSTANCECONFIG.fields_by_name['devlink'].message_type = devcommon__pb2._ADAPTER
_SERVICEINSTANCECONFIG.fields_by_name['cfg'].message_type = _SERVICEOPAQUECONFIG
_SERVICEINSTANCECONFIG.fields_by_name['lispCfg'].message_type = _SERVICELISPCONFIG
DESCRIPTOR.message_types_by_name['ServiceOpaqueConfig'] = _SERVICEOPAQUECONFIG
DESCRIPTOR.message_types_by_name['ServiceLispConfig'] = _SERVICELISPCONFIG
DESCRIPTOR.message_types_by_name['ServiceInstanceConfig'] = _SERVICEINSTANCECONFIG
DESCRIPTOR.enum_types_by_name['ZSrvType'] = _ZSRVTYPE

ServiceOpaqueConfig = _reflection.GeneratedProtocolMessageType('ServiceOpaqueConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEOPAQUECONFIG,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceOpaqueConfig)
  ))
_sym_db.RegisterMessage(ServiceOpaqueConfig)

ServiceLispConfig = _reflection.GeneratedProtocolMessageType('ServiceLispConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVICELISPCONFIG,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceLispConfig)
  ))
_sym_db.RegisterMessage(ServiceLispConfig)

ServiceInstanceConfig = _reflection.GeneratedProtocolMessageType('ServiceInstanceConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEINSTANCECONFIG,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceInstanceConfig)
  ))
_sym_db.RegisterMessage(ServiceInstanceConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037com.zededa.cloud.uservice.protoZ$github.com/zededa/eve/sdk/go/zconfig'))
# @@protoc_insertion_point(module_scope)
