// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netconfig.proto

package zconfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NetworkConfig struct {
	Id   string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type NetworkType `protobuf:"varint,5,opt,name=type,enum=NetworkType" json:"type,omitempty"`
	// Types that are valid to be assigned to NetContent:
	//	*NetworkConfig_Nlisp
	//	*NetworkConfig_Nv4
	//	*NetworkConfig_Nv6
	NetContent isNetworkConfig_NetContent `protobuf_oneof:"netContent"`
}

func (m *NetworkConfig) Reset()                    { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string            { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()               {}
func (*NetworkConfig) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

type isNetworkConfig_NetContent interface {
	isNetworkConfig_NetContent()
}

type NetworkConfig_Nlisp struct {
	Nlisp *Lispspec `protobuf:"bytes,9,opt,name=nlisp,oneof"`
}
type NetworkConfig_Nv4 struct {
	Nv4 *Ipv4Spec `protobuf:"bytes,10,opt,name=nv4,oneof"`
}
type NetworkConfig_Nv6 struct {
	Nv6 *Ipv6Spec `protobuf:"bytes,11,opt,name=nv6,oneof"`
}

func (*NetworkConfig_Nlisp) isNetworkConfig_NetContent() {}
func (*NetworkConfig_Nv4) isNetworkConfig_NetContent()   {}
func (*NetworkConfig_Nv6) isNetworkConfig_NetContent()   {}

func (m *NetworkConfig) GetNetContent() isNetworkConfig_NetContent {
	if m != nil {
		return m.NetContent
	}
	return nil
}

func (m *NetworkConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetworkConfig) GetType() NetworkType {
	if m != nil {
		return m.Type
	}
	return NetworkType_NETWORKTYPENOOP
}

func (m *NetworkConfig) GetNlisp() *Lispspec {
	if x, ok := m.GetNetContent().(*NetworkConfig_Nlisp); ok {
		return x.Nlisp
	}
	return nil
}

func (m *NetworkConfig) GetNv4() *Ipv4Spec {
	if x, ok := m.GetNetContent().(*NetworkConfig_Nv4); ok {
		return x.Nv4
	}
	return nil
}

func (m *NetworkConfig) GetNv6() *Ipv6Spec {
	if x, ok := m.GetNetContent().(*NetworkConfig_Nv6); ok {
		return x.Nv6
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NetworkConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NetworkConfig_OneofMarshaler, _NetworkConfig_OneofUnmarshaler, _NetworkConfig_OneofSizer, []interface{}{
		(*NetworkConfig_Nlisp)(nil),
		(*NetworkConfig_Nv4)(nil),
		(*NetworkConfig_Nv6)(nil),
	}
}

func _NetworkConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NetworkConfig)
	// netContent
	switch x := m.NetContent.(type) {
	case *NetworkConfig_Nlisp:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Nlisp); err != nil {
			return err
		}
	case *NetworkConfig_Nv4:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Nv4); err != nil {
			return err
		}
	case *NetworkConfig_Nv6:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Nv6); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NetworkConfig.NetContent has unexpected type %T", x)
	}
	return nil
}

func _NetworkConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NetworkConfig)
	switch tag {
	case 9: // netContent.nlisp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Lispspec)
		err := b.DecodeMessage(msg)
		m.NetContent = &NetworkConfig_Nlisp{msg}
		return true, err
	case 10: // netContent.nv4
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ipv4Spec)
		err := b.DecodeMessage(msg)
		m.NetContent = &NetworkConfig_Nv4{msg}
		return true, err
	case 11: // netContent.nv6
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ipv6Spec)
		err := b.DecodeMessage(msg)
		m.NetContent = &NetworkConfig_Nv6{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NetworkConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NetworkConfig)
	// netContent
	switch x := m.NetContent.(type) {
	case *NetworkConfig_Nlisp:
		s := proto.Size(x.Nlisp)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NetworkConfig_Nv4:
		s := proto.Size(x.Nv4)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NetworkConfig_Nv6:
		s := proto.Size(x.Nv6)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NetworkAdapter struct {
	// this is deviceName....
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	NetworkId string `protobuf:"bytes,3,opt,name=networkId" json:"networkId,omitempty"`
	// eid=lisp, v4=ipv4 etc...
	Addr     string `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	Hostname string `protobuf:"bytes,5,opt,name=hostname" json:"hostname,omitempty"`
	// more configuration for getting addr
	Lispsignature string `protobuf:"bytes,6,opt,name=lispsignature" json:"lispsignature,omitempty"`
	Pemcert       []byte `protobuf:"bytes,7,opt,name=pemcert,proto3" json:"pemcert,omitempty"`
	Pemprivatekey []byte `protobuf:"bytes,8,opt,name=pemprivatekey,proto3" json:"pemprivatekey,omitempty"`
	// used in case of P2V, where we want to specify a macAddress
	// to vif, that is simulated towards app
	MacAddress string `protobuf:"bytes,9,opt,name=macAddress" json:"macAddress,omitempty"`
	// firewall
	Acls []*ACE `protobuf:"bytes,40,rep,name=acls" json:"acls,omitempty"`
}

func (m *NetworkAdapter) Reset()                    { *m = NetworkAdapter{} }
func (m *NetworkAdapter) String() string            { return proto.CompactTextString(m) }
func (*NetworkAdapter) ProtoMessage()               {}
func (*NetworkAdapter) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *NetworkAdapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkAdapter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetworkAdapter) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *NetworkAdapter) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NetworkAdapter) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NetworkAdapter) GetLispsignature() string {
	if m != nil {
		return m.Lispsignature
	}
	return ""
}

func (m *NetworkAdapter) GetPemcert() []byte {
	if m != nil {
		return m.Pemcert
	}
	return nil
}

func (m *NetworkAdapter) GetPemprivatekey() []byte {
	if m != nil {
		return m.Pemprivatekey
	}
	return nil
}

func (m *NetworkAdapter) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *NetworkAdapter) GetAcls() []*ACE {
	if m != nil {
		return m.Acls
	}
	return nil
}

func init() {
	proto.RegisterType((*NetworkConfig)(nil), "NetworkConfig")
	proto.RegisterType((*NetworkAdapter)(nil), "NetworkAdapter")
}

func init() { proto.RegisterFile("netconfig.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0x2b, 0x59, 0x4e, 0xac, 0xb3, 0xe2, 0x02, 0x9c, 0x88, 0xa0, 0x69, 0xd5, 0xa0, 0x83,
	0x26, 0x1a, 0x70, 0x03, 0xcf, 0x75, 0x8c, 0x02, 0xed, 0xd2, 0x41, 0xe8, 0xd4, 0x8d, 0x21, 0x2f,
	0x0e, 0x11, 0x8b, 0x24, 0x28, 0x4a, 0x81, 0xf3, 0x38, 0x7d, 0x82, 0x3e, 0x62, 0x21, 0x52, 0xb5,
	0xeb, 0xed, 0xfe, 0xef, 0xff, 0xef, 0x70, 0x27, 0x11, 0xde, 0x6a, 0xf4, 0xc2, 0xe8, 0x47, 0xb5,
	0x63, 0xd6, 0x19, 0x6f, 0xae, 0x67, 0x8f, 0x2f, 0x63, 0x55, 0x0c, 0x56, 0xa3, 0xa3, 0xba, 0xfd,
	0x93, 0xc0, 0xd5, 0x0f, 0xf4, 0x2f, 0xc6, 0x3d, 0x6f, 0x43, 0x9e, 0x2c, 0x20, 0x55, 0x92, 0x26,
	0x65, 0x52, 0xe5, 0x75, 0xaa, 0x24, 0x29, 0x21, 0xf3, 0x07, 0x8b, 0x74, 0x5a, 0x26, 0xd5, 0x62,
	0x55, 0xb0, 0x31, 0xfd, 0xf3, 0x60, 0xb1, 0x0e, 0x0e, 0xf9, 0x08, 0x53, 0xbd, 0x57, 0xad, 0xa5,
	0x79, 0x99, 0x54, 0xf3, 0x55, 0xce, 0x06, 0xd1, 0x5a, 0x14, 0xdf, 0xde, 0xd4, 0xd1, 0x21, 0x37,
	0x30, 0xd1, 0xfd, 0x1d, 0x85, 0x31, 0xa0, 0x6c, 0x7f, 0x37, 0x06, 0x06, 0x1e, 0xed, 0x35, 0x9d,
	0x9f, 0xec, 0xf5, 0xc9, 0x5e, 0xdf, 0x17, 0x00, 0x1a, 0xfd, 0xd6, 0x68, 0x8f, 0xda, 0xdf, 0xfe,
	0x4e, 0x61, 0x31, 0x2e, 0xb1, 0x91, 0xdc, 0x7a, 0x74, 0x84, 0x40, 0xa6, 0x79, 0x83, 0xe3, 0xd6,
	0xa1, 0x1e, 0xef, 0x48, 0x8f, 0x77, 0xbc, 0x83, 0x5c, 0xc7, 0xae, 0xef, 0x92, 0x4e, 0x02, 0x3e,
	0x81, 0x61, 0x02, 0x97, 0xd2, 0xd1, 0x2c, 0x4e, 0x18, 0x6a, 0x72, 0x0d, 0xb3, 0x27, 0xd3, 0xfa,
	0x30, 0x79, 0x1a, 0xf8, 0x51, 0x93, 0x4f, 0x70, 0x15, 0xae, 0x54, 0x3b, 0xcd, 0x7d, 0xe7, 0x90,
	0x5e, 0x84, 0xc0, 0x39, 0x24, 0x14, 0x2e, 0x2d, 0x36, 0x02, 0x9d, 0xa7, 0x97, 0x65, 0x52, 0x15,
	0xf5, 0x3f, 0x39, 0xf4, 0x5b, 0x6c, 0xac, 0x53, 0x3d, 0xf7, 0xf8, 0x8c, 0x07, 0x3a, 0x0b, 0xfe,
	0x39, 0x24, 0xef, 0x01, 0x1a, 0x2e, 0x36, 0x52, 0x3a, 0x6c, 0xdb, 0xf0, 0x79, 0xf3, 0xfa, 0x3f,
	0x42, 0x28, 0x64, 0x5c, 0xec, 0x5b, 0x5a, 0x95, 0x93, 0x6a, 0xbe, 0xca, 0xd8, 0x66, 0xfb, 0xb5,
	0x0e, 0xe4, 0xfe, 0x0b, 0x7c, 0x10, 0xa6, 0x61, 0xaf, 0x28, 0x51, 0x72, 0x26, 0xf6, 0xa6, 0x93,
	0xac, 0x6b, 0xd1, 0xf5, 0x4a, 0x60, 0xfc, 0xf5, 0xbf, 0x6e, 0x76, 0xca, 0x3f, 0x75, 0x0f, 0x4c,
	0x98, 0x66, 0x19, 0x73, 0x4b, 0x6e, 0xd5, 0xf2, 0x35, 0xbe, 0x9b, 0x87, 0x8b, 0x90, 0xfa, 0xfc,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x47, 0x73, 0x23, 0x13, 0x4b, 0x02, 0x00, 0x00,
}
