# Copyright (c) 2025, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
version: "2"
linters:
  default: all
  disable:
    - cyclop
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godot
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          allow:
            - $gostd
            - $ven
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
