# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attest.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\037com.zededa.cloud.uservice.protoZ#github.com/lf-edge/eve/api/go/certs'),
  serialized_pb=_b('\n\x0c\x61ttest.proto\"%\n\x0fZAttestNonceReq\x12\x12\n\ndeviceUuid\x18\x01 \x01(\t\"!\n\x10ZAttestNonceResp\x12\r\n\x05nonce\x18\x01 \x01(\t\"L\n\x0fZAttestQuoteReq\x12\x12\n\ndeviceUuid\x18\x01 \x01(\t\x12\x12\n\nattestData\x18\x02 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\t\":\n\x10ZAttestQuoteResp\x12&\n\x08response\x18\x01 \x01(\x0e\x32\x14.ZAttestResponseCode*O\n\x13ZAttestResponseCode\x12\x1b\n\x17\x41TTEST_RESPONSE_SUCCESS\x10\x00\x12\x1b\n\x17\x41TTEST_RESPONSE_FAILURE\x10\x01\x42\x46\n\x1f\x63om.zededa.cloud.uservice.protoZ#github.com/lf-edge/eve/api/go/certsb\x06proto3')
)

_ZATTESTRESPONSECODE = _descriptor.EnumDescriptor(
  name='ZAttestResponseCode',
  full_name='ZAttestResponseCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ATTEST_RESPONSE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTEST_RESPONSE_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=228,
  serialized_end=307,
)
_sym_db.RegisterEnumDescriptor(_ZATTESTRESPONSECODE)

ZAttestResponseCode = enum_type_wrapper.EnumTypeWrapper(_ZATTESTRESPONSECODE)
ATTEST_RESPONSE_SUCCESS = 0
ATTEST_RESPONSE_FAILURE = 1



_ZATTESTNONCEREQ = _descriptor.Descriptor(
  name='ZAttestNonceReq',
  full_name='ZAttestNonceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceUuid', full_name='ZAttestNonceReq.deviceUuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=53,
)


_ZATTESTNONCERESP = _descriptor.Descriptor(
  name='ZAttestNonceResp',
  full_name='ZAttestNonceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='ZAttestNonceResp.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=88,
)


_ZATTESTQUOTEREQ = _descriptor.Descriptor(
  name='ZAttestQuoteReq',
  full_name='ZAttestQuoteReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceUuid', full_name='ZAttestQuoteReq.deviceUuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attestData', full_name='ZAttestQuoteReq.attestData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='ZAttestQuoteReq.signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=166,
)


_ZATTESTQUOTERESP = _descriptor.Descriptor(
  name='ZAttestQuoteResp',
  full_name='ZAttestQuoteResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ZAttestQuoteResp.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=226,
)

_ZATTESTQUOTERESP.fields_by_name['response'].enum_type = _ZATTESTRESPONSECODE
DESCRIPTOR.message_types_by_name['ZAttestNonceReq'] = _ZATTESTNONCEREQ
DESCRIPTOR.message_types_by_name['ZAttestNonceResp'] = _ZATTESTNONCERESP
DESCRIPTOR.message_types_by_name['ZAttestQuoteReq'] = _ZATTESTQUOTEREQ
DESCRIPTOR.message_types_by_name['ZAttestQuoteResp'] = _ZATTESTQUOTERESP
DESCRIPTOR.enum_types_by_name['ZAttestResponseCode'] = _ZATTESTRESPONSECODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZAttestNonceReq = _reflection.GeneratedProtocolMessageType('ZAttestNonceReq', (_message.Message,), dict(
  DESCRIPTOR = _ZATTESTNONCEREQ,
  __module__ = 'attest_pb2'
  # @@protoc_insertion_point(class_scope:ZAttestNonceReq)
  ))
_sym_db.RegisterMessage(ZAttestNonceReq)

ZAttestNonceResp = _reflection.GeneratedProtocolMessageType('ZAttestNonceResp', (_message.Message,), dict(
  DESCRIPTOR = _ZATTESTNONCERESP,
  __module__ = 'attest_pb2'
  # @@protoc_insertion_point(class_scope:ZAttestNonceResp)
  ))
_sym_db.RegisterMessage(ZAttestNonceResp)

ZAttestQuoteReq = _reflection.GeneratedProtocolMessageType('ZAttestQuoteReq', (_message.Message,), dict(
  DESCRIPTOR = _ZATTESTQUOTEREQ,
  __module__ = 'attest_pb2'
  # @@protoc_insertion_point(class_scope:ZAttestQuoteReq)
  ))
_sym_db.RegisterMessage(ZAttestQuoteReq)

ZAttestQuoteResp = _reflection.GeneratedProtocolMessageType('ZAttestQuoteResp', (_message.Message,), dict(
  DESCRIPTOR = _ZATTESTQUOTERESP,
  __module__ = 'attest_pb2'
  # @@protoc_insertion_point(class_scope:ZAttestQuoteResp)
  ))
_sym_db.RegisterMessage(ZAttestQuoteResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
