#!/bin/sh

# PID of the started entrypoint container process.
# PID file is created from the `init-initrd` script.
PID_FILE="/mnt/entrypoint-pid"

if [ ! -f "$PID_FILE" ]; then
    echo "Error: PID file '$PID_FILE' not found. Container did not start?"
    exit 1
fi

PID=$(cat "$PID_FILE")

# Check if the first argument is provided, otherwise use /bin/sh as the default
PROGRAM=${1:-/bin/sh}

# Shift arguments if a program is provided, so "$@" contains the rest of the command-line arguments
shift

# Enter the namespaces and execute the specified program with its arguments
nsenter -t "$PID" -m -u -i -n -p -r/mnt/rootfs -w/mnt/rootfs "$PROGRAM" "$@"
