FROM ZTOOLS_TAG as ztools
FROM XENTOOLS_TAG as xen-tools
FROM DNSMASQ_TAG as dnsmasq
FROM TESTMSVCS_TAG as msvcs
FROM GPTTOOLS_TAG as gpttools

FROM alpine:3.6
RUN apk add --no-cache \
    yajl xz bash openssl iptables ip6tables \
    coreutils dmidecode sudo libbz2 libuuid ipset \
    libpcap libaio pixman glib curl radvd perl ethtool \
    openssh-server util-linux

# The following enables pcappy to dlopen libpcap.so
RUN ln -s libpcap.so.1 /usr/lib/libpcap.so

# FIXME: we really need to do a proper linuxkit sshd
RUN ssh-keygen -A ; echo PermitRootLogin yes >> /etc/ssh/sshd_config ; sed -ie '/^root/s#^.*$#root:$6$Ndt1G5AYZFQ8rz7m$7vGZMKKotSYxwxk/.jMfuOCzxw0I3DNedygaQaLF7kYSYsLqiBHhmc8RJSXp8/VxSYPpgYSz/8fkv0hO6I4js.:17477:0:::::#' /etc/shadow

COPY --from=xen-tools / /
COPY --from=ztools / /
COPY --from=gpttools / /
COPY --from=dnsmasq /usr/sbin/dnsmasq /opt/zededa/bin/dnsmasq
COPY --from=msvcs /vms /vms

# And now a few local tweaks
COPY rootfs/ /

# FIXME: replace with tini+monit ASAP
CMD /init.sh
