#!/bin/sh
#
# Script which handles the routing issues as necessary for pppd
# Only the link to Newman requires this handling.
#

cat <<__EOT__
When the ppp link comes up, this script is called with the following
parameters
       $1      the interface name used by pppd (e.g. ppp3)
       $2      the tty device name
       $3      the tty device speed
       $4      the local IP address for the interface
       $5      the remote IP address
       $6      the parameter specified by the 'ipparam' option to pppd
__EOT__

# route del default
route add default $1

# this variable is only set if the usepeerdns pppd option is being used
[ "$USEPEERDNS" ] || exit 0

# exit if the resolvconf package is installed
[ -x /sbin/resolvconf ] && exit 0

# create the file if it does not exist
if [ ! -e /etc/resolv.conf ]; then
  : > /etc/resolv.conf
fi

# follow any symlink to find the real file
REALRESOLVCONF=$(readlink --canonicalize /etc/resolv.conf)

# merge the new nameservers with the other options from the old configuration
{
  cat /var/run/ppp/resolv.conf
  grep -v '^nameserver[[:space:]]' "$REALRESOLVCONF" || true
} > "$REALRESOLVCONF.tmp"

# backup the old configuration and install the new one
cp -a "$REALRESOLVCONF" "$REALRESOLVCONF.pppd-backup.$PPP_IFACE"
mv -f "$REALRESOLVCONF.tmp" "$REALRESOLVCONF"

# restart nscd because resolv.conf has changed
if [ -e /var/run/nscd.pid ]; then
  /etc/init.d/nscd restart || true
fi

exit 0
