#!/bin/sh
# shellcheck disable=SC2046,SC2086
if [ "$1" = console ]; then
   exec chroot /hostfs /usr/bin/ctr --namespace services.linuxkit t exec --cwd / ${TERM:+-t} --exec-id xl xen-tools env ${TERM:+TERM=}$TERM xl "$@"
else
   exec chroot /hostfs /usr/bin/ctr --namespace services.linuxkit t exec --cwd / --exec-id xl xen-tools xl "$@"
fi
