---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-read-access
  labels:
    kubevirt.io: ""
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/vnc
      - virtualmachineinstances/console
    verbs:
      - get
  - apiGroups:
      - kubevirt.io
    resources:
      - kubevirts
      - virtualmachines
      - virtualmachineinstances
      - virtualmachineinstancepresets
      - virtualmachineinstancereplicasets
    verbs:
      - get
      - list
  - apiGroups:
      - longhorn.io
    resources:
      - volumes
      - volumes/status
      - replicas
      - replicas/status
      - nodes
      - nodes/status
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-read-access-binding
subjects:
  - kind: User
    name: debugging-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: vm-read-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debugging-cluster-role
rules:
  - apiGroups: ["", "apps", "extensions", "k8s.cni.cncf.io", "apiextensions.k8s.io"]
    resources: ['*']
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debugging-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: debugging-cluster-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: debugging-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: debugging-exec-role
  namespace: eve-kube-app
rules:
  - apiGroups: [""]
    resources: ['pods/exec']
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debugging-exec-role-binding
  namespace: eve-kube-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: debugging-exec-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: debugging-user
