# Copyright (c) 2024 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
# Override default policy to rebalance eve apps when descheduler is run.
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: EveAppNodeAffinity
        pluginConfig:
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            namespaces:
              include:
              - "eve-kube-app"
            nodeAffinityType:
            - "preferredDuringSchedulingIgnoredDuringExecution"
        plugins:
          deschedule:
            enabled:
              - "RemovePodsViolatingNodeAffinity"
