# EVE Memory Testing Configuration
# Generated by Terraform

# System Configuration
TOTAL_RAM_MB=${total_ram_mb}
AVAILABLE_RAM_MB=${available_ram_mb}
SAFE_MAX_MB=${safe_max_mb}
AGGRESSIVE_MAX_MB=${aggressive_max_mb}

# Test Configuration
TEST_DURATION_MINUTES=${test_duration}
MAX_CONTAINERS=${max_containers}

# Calculated Values
SAFE_ALLOCATION_PERCENT=90
AGGRESSIVE_ALLOCATION_PERCENT=95
EXTREME_ALLOCATION_PERCENT=105
