// Copyright (c) 2026 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

package utils

import (
	"crypto/sha1"
	"fmt"
	"math/rand"
	"net"
	"strconv"
	"time"
)

// GenerateMAC returns a deterministic, locally administered, unicast MAC address
// derived from the device name and interface name.
//
// The MAC is generated by hashing stable identifiers to ensure that:
//   - the same device/interface pair always receives the same MAC,
//   - MAC addresses remain consistent across restarts,
//   - collisions are highly unlikely,
//   - the address does not conflict with real hardware.
//
// The locally administered bit is set and the multicast bit is cleared
// to guarantee the MAC is valid for use in virtualized environments.
func GenerateMAC(devName, ifaceName string) net.HardwareAddr {
	// Use a hash to get deterministic entropy
	h := sha1.Sum([]byte(devName + ":" + ifaceName))

	mac := make(net.HardwareAddr, 6)
	copy(mac, h[:6])

	// Set locally administered bit (bit 1 of first octet)
	mac[0] |= 0x02

	// Clear multicast bit (bit 0 of first octet)
	mac[0] &^= 0x01

	return mac
}

// FindUnusedPort picks a random unused TCP port on the given host IP by probing it.
func FindUnusedPort(hostIP net.IP) (uint16, error) {
	if hostIP == nil {
		return 0, fmt.Errorf("undefined host IP")
	}

	const (
		// default range for ephemeral ports (as defined by IANA)
		minPort   = 49152
		maxPort   = 65535
		maxTrials = 50
	)

	for i := 0; i < maxTrials; i++ {
		port := uint16(rand.Intn(maxPort-minPort+1) + minPort)
		addr := net.JoinHostPort(hostIP.String(), strconv.Itoa(int(port)))
		conn, err := net.DialTimeout("tcp", addr, time.Second)
		if err != nil {
			// If connection is refused or times out, assume port is unused.
			return port, nil
		}
		// Connection succeeded → port in use.
		_ = conn.Close()
	}

	return 0, fmt.Errorf("failed to find unused port on %s after %d attempts",
		hostIP, maxTrials)
}
