image: eve-watchdog
org: lfedge
config:
  binds:
    - /run:/run
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /persist:/persist
    - /usr/bin/ctr:/usr/bin/ctr
  pid: host
  capabilities:
    - all
  devices:
    - path: all
      type: a
