image: eve-xen-tools
org: lfedge
network: yes
config:
  binds:
    - /run:/run
    - /dev:/dev
    - /dev/pts:/dev/pts
    - /etc/resolv.conf:/etc/resolv.conf
    - /var/persist:/persist
    - /:/hostfs
  net: host
  capabilities:
    - all
  pid: host
  userns: host
