#!/bin/sh

bail() {
   echo "$@"
   exit 1
}

# pre-flight checks
[ $# -ne 1 ] && bail "Usage: $0 <domain name>"

# find the domain
# Sometimes after EVE reboot, we called xen-info before xen-start finished executing,
# which led to domian not found error. To prevent that, we wait for sometime for the domain to come up.
waited=0
ID=$(xl domid "$1" 2>/dev/null)
while [ -z "$ID" ] && [ "$waited" -lt 60 ]; do
        ID=$(xl domid "$1" 2>/dev/null)
        sleep 3
        waited=$((waited + 3))
done
[ -z "$ID" ] && bail "Couldn't find domain ID for domain $1"

# we expect to get rbpscd where every letter can also be a dash (-)
# Name    ID    Mem    VCPUs    State    Time(s)
case $(xl list "$ID" | awk '{st=$5;} END {print st;}') in
   *d) STATUS=halting ;;
  *c*) STATUS=broken  ;;
  *s*) STATUS=halting ;;
  *p*) STATUS=paused  ;;
  *b*) STATUS=running ;;
   r*) STATUS=running ;;
    *) STATUS=$(cat /dev/status) ;;
esac

# an additional check we do for running domains is to make sure device model is still around
if [ "$STATUS" = running ] &&
   DM_PID=$(xenstore read "/local/domain/$ID/image/device-model-pid") &&
   ! (readlink "/proc/$DM_PID/exe" | grep -q qemu-system-); then
   STATUS=broken
fi

# finally deposit the current status
echo "$STATUS" | tee /dev/status
