#!/bin/sh
set -ex

bail() {
   echo "$@"
   exit 1
}

# pre-flight checks
[ $# -ne 2 ] && bail "Usage: $0 <domain name> <domain config>"

# FIXME: this really needs to be managed by runc
keyctl link @u @s || :

# create domain in a paused state
xl create "$2" -p

# we may need to wait for domain to come online for us to manipulate it (timing out in under 30 sec)
for i in 1 2 3; do
  ID=$(xl domid "$1" 2>/dev/null)
  sleep 8
  [ -z "$ID" ] || break
done
[ -z "$ID" ] && bail "Couldn't find domain $1"

# finally unpause the domain
xl unpause "$ID"

# declare the status as running
echo running > /dev/status

# and start watching over the console
exec xl console "$ID" < /dev/null
