#hadolint ignore=DL3006
FROM DEBUG_TAG as musl-build
#hadolint ignore=DL3006
FROM KERNEL_TAG as kernel-build
FROM alpine:3.12 as vtune-build

RUN apk add --no-cache curl=7.69.1-r3 tar=1.32-r1 make=4.3-r0 linux-headers=5.4.5-r1 patch=2.7.6-r6 g++=9.3.0-r2 \
                       coreutils=8.32-r0 git=2.26.2-r0

WORKDIR /

#hadolint ignore=DL3010
COPY --from=kernel-build /kernel.tar /
#hadolint ignore=DL3010
COPY --from=kernel-build /kernel-dev.tar /
RUN tar xf kernel.tar
RUN tar xf kernel-dev.tar

RUN git clone --depth=1 https://github.com/intel/aca.git
COPY sepdk/*.py aca/sepdk/src/

RUN mkdir -p /vtune/bin
WORKDIR /aca/agentdk
RUN make && mv sepagent /vtune/bin/
WORKDIR /aca/sepdk/src
RUN sh build-driver --kernel-version="$(ls -1 /lib/modules)" --install-dir=/vtune

RUN ldd /vtune/bin/sepagent

FROM linuxkit/sshd:666b4a1a323140aa1f332826164afba506abf597

# get the rebuilt musl from above
COPY --from=musl-build /lib/ld-musl-*.so.1 /lib/

COPY --from=vtune-build /vtune/* /
