# syntax=docker/dockerfile-upstream:1.5.0-rc2-labs

# hadolint ignore=DL3006
FROM XENTOOLS_TAG AS initrd-build
# hadolint ignore=DL3006
FROM KERNEL_TAG AS kernel-build

FROM scratch
COPY --from=initrd-build --chmod=666 /usr/lib/xen/boot/runx-initrd /
COPY --from=kernel-build --chmod=666 /kernel /
