# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certs/certs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evecommon import evecommon_pb2 as evecommon_dot_evecommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x65rts/certs.proto\x12\x14org.lfedge.eve.certs\x1a\x19\x65vecommon/evecommon.proto\"=\n\x0fZControllerCert\x12*\n\x05\x63\x65rts\x18\x01 \x03(\x0b\x32\x1b.org.lfedge.eve.certs.ZCert\"Y\n\rZCertMetaData\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.org.lfedge.eve.certs.ZCertMetaDataType\x12\x11\n\tmeta_data\x18\x02 \x01(\x0c\"\x81\x02\n\x05ZCert\x12\x36\n\x08hashAlgo\x18\x01 \x01(\x0e\x32$.org.lfedge.eve.common.HashAlgorithm\x12\x10\n\x08\x63\x65rtHash\x18\x02 \x01(\x0c\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x1f.org.lfedge.eve.certs.ZCertType\x12\x0c\n\x04\x63\x65rt\x18\x04 \x01(\x0c\x12\x33\n\nattributes\x18\x05 \x01(\x0b\x32\x1f.org.lfedge.eve.certs.ZCertAttr\x12<\n\x0fmeta_data_items\x18\x06 \x03(\x0b\x32#.org.lfedge.eve.certs.ZCertMetaData\"/\n\tZCertAttr\x12\x12\n\nis_mutable\x18\x01 \x01(\x08\x12\x0e\n\x06is_tpm\x18\x02 \x01(\x08*]\n\x11ZCertMetaDataType\x12!\n\x1dZ_CERT_META_DATA_TYPE_INVALID\x10\x00\x12%\n!Z_CERT_META_DATA_TYPE_TPM2_PUBLIC\x10\x01*\xaf\x02\n\tZCertType\x12\x1d\n\x19\x43\x45RT_TYPE_CONTROLLER_NONE\x10\x00\x12 \n\x1c\x43\x45RT_TYPE_CONTROLLER_SIGNING\x10\x01\x12%\n!CERT_TYPE_CONTROLLER_INTERMEDIATE\x10\x02\x12&\n\"CERT_TYPE_CONTROLLER_ECDH_EXCHANGE\x10\x03\x12\x1f\n\x1b\x43\x45RT_TYPE_DEVICE_ONBOARDING\x10\n\x12\'\n#CERT_TYPE_DEVICE_RESTRICTED_SIGNING\x10\x0b\x12$\n CERT_TYPE_DEVICE_ENDORSEMENT_RSA\x10\x0c\x12\"\n\x1e\x43\x45RT_TYPE_DEVICE_ECDH_EXCHANGE\x10\rB;\n\x14org.lfedge.eve.certsZ#github.com/lf-edge/eve/api/go/certsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'certs.certs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.lfedge.eve.certsZ#github.com/lf-edge/eve/api/go/certs'
  _ZCERTMETADATATYPE._serialized_start=533
  _ZCERTMETADATATYPE._serialized_end=626
  _ZCERTTYPE._serialized_start=629
  _ZCERTTYPE._serialized_end=932
  _ZCONTROLLERCERT._serialized_start=70
  _ZCONTROLLERCERT._serialized_end=131
  _ZCERTMETADATA._serialized_start=133
  _ZCERTMETADATA._serialized_end=222
  _ZCERT._serialized_start=225
  _ZCERT._serialized_end=482
  _ZCERTATTR._serialized_start=484
  _ZCERTATTR._serialized_end=531
# @@protoc_insertion_point(module_scope)
