# Copyright (c) 2026, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
name: Fuzz Tests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"
    paths-ignore:
      - '**/*.md'
      - '.github/**'

jobs:
  fuzz:
    runs-on: zededa-ubuntu-2204
    env:
      REPO_NAME: ${{ github.event.repository.full_name }}
      GH_REF: ${{ github.ref }}
    steps:
      - name: Starting Report
        run: |
          echo Git Ref: ${GH_REF}
          echo GitHub Event: ${{ github.event_name }}
          echo Disk usage
          df -h
          echo Memory
          free -m
      - name: Clear repository
        run: |
          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
          rm -fr ~/.linuxkit
          docker system prune --all --force --volumes
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        if: ${{ github.event.repository.full_name == 'lf-edge/eve' }}
        run: | # Runners must provide default credentials
          docker login
      - name: Fuzz Test
        run: |
          make -C pkg/pillar fuzz-test
      - name: Clean
        if: ${{ always() }}
        run: |
          make clean || :
          docker system prune -f -a || :
          docker rm -f $(docker ps -aq) && docker volume rm -f $(docker volume ls -q) || :
          rm -rf ~/.linuxkit || :
