// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netconfig.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkConfig struct {
	Id             string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuidandversion *UUIDandVersion `protobuf:"bytes,2,opt,name=uuidandversion,proto3" json:"uuidandversion,omitempty"`
	Type           NetworkType     `protobuf:"varint,5,opt,name=type,proto3,enum=NetworkType" json:"type,omitempty"`
	// network ip specification
	Ip  *Ipspec               `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Dns []*ZnetStaticDNSEntry `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`
	// enterprise proxy
	EntProxy             *ProxyConfig `protobuf:"bytes,8,opt,name=entProxy,proto3" json:"entProxy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NetworkConfig) Reset()         { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()    {}
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aa19e8dfa9a5274, []int{0}
}

func (m *NetworkConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkConfig.Unmarshal(m, b)
}
func (m *NetworkConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkConfig.Marshal(b, m, deterministic)
}
func (m *NetworkConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkConfig.Merge(m, src)
}
func (m *NetworkConfig) XXX_Size() int {
	return xxx_messageInfo_NetworkConfig.Size(m)
}
func (m *NetworkConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkConfig proto.InternalMessageInfo

func (m *NetworkConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetworkConfig) GetUuidandversion() *UUIDandVersion {
	if m != nil {
		return m.Uuidandversion
	}
	return nil
}

func (m *NetworkConfig) GetType() NetworkType {
	if m != nil {
		return m.Type
	}
	return NetworkType_NETWORKTYPENOOP
}

func (m *NetworkConfig) GetIp() *Ipspec {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *NetworkConfig) GetDns() []*ZnetStaticDNSEntry {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *NetworkConfig) GetEntProxy() *ProxyConfig {
	if m != nil {
		return m.EntProxy
	}
	return nil
}

type NetworkAdapter struct {
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NetworkId string `protobuf:"bytes,3,opt,name=networkId,proto3" json:"networkId,omitempty"`
	Addr      string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Hostname  string `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// more configuration for getting addr/EID
	CryptoEid     string `protobuf:"bytes,10,opt,name=cryptoEid,proto3" json:"cryptoEid,omitempty"`
	Lispsignature string `protobuf:"bytes,6,opt,name=lispsignature,proto3" json:"lispsignature,omitempty"`
	Pemcert       []byte `protobuf:"bytes,7,opt,name=pemcert,proto3" json:"pemcert,omitempty"`
	Pemprivatekey []byte `protobuf:"bytes,8,opt,name=pemprivatekey,proto3" json:"pemprivatekey,omitempty"`
	// Used in case of P2V, where we want to specify a macAddress
	// to vif, that is simulated towards app
	MacAddress string `protobuf:"bytes,9,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	// firewall
	Acls                 []*ACE   `protobuf:"bytes,40,rep,name=acls,proto3" json:"acls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkAdapter) Reset()         { *m = NetworkAdapter{} }
func (m *NetworkAdapter) String() string { return proto.CompactTextString(m) }
func (*NetworkAdapter) ProtoMessage()    {}
func (*NetworkAdapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aa19e8dfa9a5274, []int{1}
}

func (m *NetworkAdapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkAdapter.Unmarshal(m, b)
}
func (m *NetworkAdapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkAdapter.Marshal(b, m, deterministic)
}
func (m *NetworkAdapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAdapter.Merge(m, src)
}
func (m *NetworkAdapter) XXX_Size() int {
	return xxx_messageInfo_NetworkAdapter.Size(m)
}
func (m *NetworkAdapter) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAdapter.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAdapter proto.InternalMessageInfo

func (m *NetworkAdapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkAdapter) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *NetworkAdapter) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NetworkAdapter) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NetworkAdapter) GetCryptoEid() string {
	if m != nil {
		return m.CryptoEid
	}
	return ""
}

func (m *NetworkAdapter) GetLispsignature() string {
	if m != nil {
		return m.Lispsignature
	}
	return ""
}

func (m *NetworkAdapter) GetPemcert() []byte {
	if m != nil {
		return m.Pemcert
	}
	return nil
}

func (m *NetworkAdapter) GetPemprivatekey() []byte {
	if m != nil {
		return m.Pemprivatekey
	}
	return nil
}

func (m *NetworkAdapter) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *NetworkAdapter) GetAcls() []*ACE {
	if m != nil {
		return m.Acls
	}
	return nil
}

func init() {
	proto.RegisterType((*NetworkConfig)(nil), "NetworkConfig")
	proto.RegisterType((*NetworkAdapter)(nil), "NetworkAdapter")
}

func init() { proto.RegisterFile("netconfig.proto", fileDescriptor_5aa19e8dfa9a5274) }

var fileDescriptor_5aa19e8dfa9a5274 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x6e, 0xdb, 0x3c,
	0x10, 0x85, 0x21, 0xd9, 0x89, 0x6d, 0x46, 0xb1, 0x01, 0xfe, 0x8b, 0x9f, 0x08, 0x8a, 0x56, 0x08,
	0x52, 0x40, 0x9b, 0x52, 0x80, 0xbb, 0xe8, 0xda, 0x4d, 0x8c, 0x22, 0x9b, 0xa0, 0x60, 0x9a, 0x2e,
	0xb2, 0x63, 0xc8, 0xb1, 0x42, 0xc4, 0x22, 0x09, 0x92, 0x52, 0xaa, 0x9e, 0xaa, 0x87, 0xea, 0x41,
	0x0a, 0x51, 0xaa, 0xdb, 0x74, 0x37, 0xef, 0x7b, 0x33, 0x6f, 0xc0, 0x01, 0xd1, 0x4a, 0x43, 0x10,
	0x46, 0xef, 0x54, 0x45, 0xad, 0x33, 0xc1, 0x9c, 0xcd, 0x77, 0xcf, 0x63, 0x95, 0xf5, 0x56, 0xad,
	0x47, 0xb5, 0x92, 0xd0, 0x0a, 0x53, 0xd7, 0x66, 0x04, 0xe7, 0x3f, 0x13, 0x74, 0x7a, 0x03, 0xe1,
	0xd9, 0xb8, 0xa7, 0xcb, 0x18, 0x80, 0x97, 0x28, 0x55, 0x92, 0x24, 0x79, 0x52, 0x2c, 0x58, 0xaa,
	0x24, 0xfe, 0x80, 0x96, 0x4d, 0xa3, 0x24, 0xd7, 0xb2, 0x05, 0xe7, 0x95, 0xd1, 0x24, 0xcd, 0x93,
	0xe2, 0x64, 0xbd, 0xa2, 0x77, 0x77, 0xd7, 0x57, 0x5c, 0xcb, 0xaf, 0x03, 0x66, 0xff, 0xb4, 0xe1,
	0x1c, 0x4d, 0x43, 0x67, 0x81, 0x1c, 0xe5, 0x49, 0xb1, 0x5c, 0x67, 0x74, 0x5c, 0xf3, 0xa5, 0xb3,
	0xc0, 0xa2, 0x83, 0xff, 0x47, 0xa9, 0xb2, 0xe4, 0x38, 0xc6, 0xcd, 0xa8, 0xb2, 0xde, 0x82, 0x60,
	0xa9, 0xb2, 0xf8, 0x2d, 0x9a, 0x48, 0xed, 0xc9, 0x2c, 0x9f, 0x14, 0x27, 0xeb, 0xff, 0xe8, 0xbd,
	0x86, 0x70, 0x1b, 0x78, 0x50, 0xe2, 0xea, 0xe6, 0x76, 0xab, 0x83, 0xeb, 0x58, 0xef, 0xe3, 0x02,
	0xcd, 0x41, 0x87, 0xcf, 0xce, 0x7c, 0xeb, 0xc8, 0x3c, 0xa6, 0x64, 0x34, 0xaa, 0xe1, 0x29, 0xec,
	0xe0, 0x9e, 0xff, 0x48, 0xd1, 0x72, 0xdc, 0xbf, 0x91, 0xdc, 0x06, 0x70, 0x18, 0xa3, 0xa9, 0xe6,
	0x35, 0x8c, 0x2f, 0x8d, 0x35, 0x7e, 0x85, 0x16, 0x7a, 0xe8, 0xba, 0x96, 0x64, 0x12, 0x8d, 0x3f,
	0xa0, 0x9f, 0xe0, 0x52, 0x3a, 0x32, 0x1d, 0x26, 0xfa, 0x1a, 0x9f, 0xa1, 0xf9, 0xa3, 0xf1, 0x21,
	0x26, 0x1d, 0x45, 0x7e, 0xd0, 0x7d, 0x9a, 0x70, 0x9d, 0x0d, 0x66, 0xab, 0x24, 0x41, 0x43, 0xda,
	0x01, 0xe0, 0x0b, 0x74, 0xba, 0x57, 0xde, 0x7a, 0x55, 0x69, 0x1e, 0x1a, 0x07, 0xf1, 0x0e, 0x0b,
	0xf6, 0x12, 0x62, 0x82, 0x66, 0x16, 0x6a, 0x01, 0x2e, 0x90, 0x59, 0x9e, 0x14, 0x19, 0xfb, 0x2d,
	0xfb, 0x79, 0x0b, 0xb5, 0x75, 0xaa, 0xe5, 0x01, 0x9e, 0x60, 0xb8, 0x40, 0xc6, 0x5e, 0x42, 0xfc,
	0x1a, 0xa1, 0x9a, 0x8b, 0x8d, 0x94, 0x0e, 0xbc, 0x27, 0x8b, 0xb8, 0xe2, 0x2f, 0x82, 0x09, 0x9a,
	0x72, 0xb1, 0xf7, 0xa4, 0x88, 0xa7, 0x9e, 0xd2, 0xcd, 0xe5, 0x96, 0x45, 0xf2, 0xf1, 0x13, 0x7a,
	0x23, 0x4c, 0x4d, 0xbf, 0x83, 0x04, 0xc9, 0xa9, 0xd8, 0x9b, 0x46, 0xd2, 0xc6, 0x83, 0x6b, 0x95,
	0x80, 0xe1, 0xf3, 0xdc, 0x5f, 0x54, 0x2a, 0x3c, 0x36, 0x0f, 0x54, 0x98, 0xba, 0xdc, 0xef, 0xde,
	0x81, 0xac, 0xa0, 0x84, 0x16, 0x4a, 0x6e, 0x55, 0x59, 0x99, 0x72, 0xf8, 0x91, 0x0f, 0xc7, 0xb1,
	0xf9, 0xfd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x51, 0x31, 0x8c, 0xa5, 0x02, 0x00, 0x00,
}
