---
image: eve-vtpm
org: lfedge
config:
  # these ids must match the corresponding container specific user/group
  # created in pkg/dom0-ztools
  uid: 101
  gid: 101
  # give container access to the host TPM device via tpms group
  additionalGids: [100]
  binds:
    - /dev:/dev
    - /run/swtpm:/run/swtpm
    - /persist/swtpm:/persist/swtpm
  devices:
    - path: all
      type: a

buildArgs:
  - REL_HASH_%=@lkt:pkgs:../*
